# This file is a template, and might need editing before it works on your project.
include:
  template: Jobs/Code-Quality.gitlab-ci.yml
java:
  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml